title: "Modern Fortran Çalışma Notları"
description: "Türkçe Modern Fortran örnekleri ve notları"
theme: jekyll-theme-primer
markdown: kramdown
url: "https://onkanat.github.io"
baseurl: "/fortran"
exclude:
  - runs
  - runs/cut
  - "*.mod"
  - assets/fortranv3.pdf
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      lang: tr
